find_program(CURL NAMES curl)

if (CURL)
    message("-- Curl detected: true")
    set(CURL_DETECTED TRUE)
    set(OTA_HOST zzuummaa.sytes.net)
    set(OTA_PORT 9443)
    set(OTA_TOKEN b4e0b3453ffb400cb6c049f401b75af2)
    add_definitions( -DOTA_TOKEN_DEF=${OTA_TOKEN} )
else()
    message("-- Curl detected: false")
endif()
